// src/utils/photoLoader.ts
import type { Photo } from "@/components/lightbox/Lightbox";
import photoDimensions from "@/utils/photoDimensions.json";

/**
 * Core shape used by the resolver.
 * Keeps your existing fields and adds slug/subfolder/folders.
 */
export type PhotoBase = {
  slug: string;        // filename without extension
  src: string;         // URL resolved by Vite
  title?: string;      // derived from filename (or set upstream)
  category?: string;   // human name of primary folder (badge text)
  subfolder: string;   // first folder under the root (e.g. "living-level")
  folders?: string[];  // all folder segments under the root
  folderPath?: string; // full folder path under the root, e.g. "living-level/kitchen"
  leafFolder?: string; // deepest folder, e.g. "kitchen" ("" for a level's loose photos)
  author?: string;     // preserved if you already set this elsewhere
  thumbSrc?: string;    // small derivative for 62-64px thumbnail strips (MIS-459)
  leadSrc?: string;     // 640px derivative for the full-width "lead" spread photo (MIS-459)
  midSrc?: string;      // 960px derivative, the srcset candidate between leadSrc and the full plate
  width?: number;       // intrinsic pixel width of the full-size plate
  height?: number;      // intrinsic pixel height of the full-size plate
};

const DIMENSIONS = photoDimensions as Record<string, { width: number; height: number }>;

// ---- Utilities ----

function toTitleCase(s: string) {
  return s
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (m) => m.toUpperCase());
}

// "bedroom-master-5.webp" -> "Bedroom Master"
export function titleFromFilename(pathOrFile: string) {
  const file = (pathOrFile.split("/").pop() || "").replace(/\.(webp|jpg|jpeg|png)$/i, "");
  const cleaned = file
    .replace(/\d+\b/g, "") // drop trailing numbers
    .replace(/\s+/g, " ")
    .trim();
  return toTitleCase(cleaned);
}

/**
 * IMPORTANT: Vite requires a LITERAL string here (no variables or `${}`).
 * We glob EVERYTHING once, then filter by subfolder in JS.
 */
const ALL_IMAGES = import.meta.glob(
  "/src/assets/everview_photos_webp/**/*.{webp,jpg,jpeg,png}",
  { eager: true, as: "url" }
) as Record<string, string>;

// 192px-wide derivatives generated by scripts/generate-thumbnails.mjs, mirroring
// the same folder/slug layout. Keyed by "<subfolder>/<slug>" below so a thumb
// resolves regardless of the original's extension.
const ALL_THUMBS = import.meta.glob(
  "/src/assets/everview_photos_webp_thumb/**/*.webp",
  { eager: true, as: "url" }
) as Record<string, string>;

// 640px-wide derivatives for the full-width "lead" spread photo in each
// space/room (HouseLevelsSection, BedroomsSection). Not every original has
// one — the generator skips originals already narrower than 640px.
const ALL_LEADS = import.meta.glob(
  "/src/assets/everview_photos_webp_lead/**/*.webp",
  { eager: true, as: "url" }
) as Record<string, string>;

// 960px-wide derivatives, the srcset candidate between the 640px lead and the
// full plate — a 2x-DPR phone needs ~780-960 device px for a lead spread, and
// 640 falls short of that. Not every original has one — the generator skips
// originals already narrower than 960px.
const ALL_MIDS = import.meta.glob(
  "/src/assets/everview_photos_webp_mid/**/*.webp",
  { eager: true, as: "url" }
) as Record<string, string>;

function thumbKey(path: string, rootFolder: string) {
  const idx = path.indexOf(`/${rootFolder}/`);
  return idx >= 0 ? path.slice(idx + rootFolder.length + 2) : path;
}

function byKey(images: Record<string, string>, rootFolder: string): Record<string, string> {
  const map: Record<string, string> = {};
  for (const [path, url] of Object.entries(images)) {
    const key = thumbKey(path, rootFolder).replace(/\.webp$/i, "");
    map[key] = url;
  }
  return map;
}

const THUMBS_BY_KEY = byKey(ALL_THUMBS, "everview_photos_webp_thumb");
const LEADS_BY_KEY = byKey(ALL_LEADS, "everview_photos_webp_lead");
const MIDS_BY_KEY = byKey(ALL_MIDS, "everview_photos_webp_mid");

function resolveDerivative(path: string, byKeyMap: Record<string, string>): string | undefined {
  const key = thumbKey(path, "everview_photos_webp").replace(/\.(webp|jpg|jpeg|png)$/i, "");
  return byKeyMap[key];
}

/**
 * ORIGINAL-style loader for Lightbox (returns Photo[]).
 * Now filters from ALL_IMAGES to avoid dynamic globs.
 */
export function loadPhotosFrom(subfolder: string, category?: string): Photo[] {
  const effectiveCategory = category ?? toTitleCase(subfolder);

  const entries = Object.entries(ALL_IMAGES)
    // Match "/everview_photos_webp/<subfolder>/" anywhere in the path
    .filter(([path]) => path.includes(`/everview_photos_webp/${subfolder}/`))
    .sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true }));

  return entries.map(([path, url]) => ({
    src: url,
    title: titleFromFilename(path),
    category: effectiveCategory,
  }));
}

/**
 * Returns PhotoBase objects for a single subfolder (flat).
 * Adds slug/subfolder/category so the resolver has what it needs.
 */
export function loadBasesFrom(subfolder: string, category?: string): PhotoBase[] {
  const effectiveCategory = category ?? toTitleCase(subfolder);

  const entries = Object.entries(ALL_IMAGES)
    .filter(([path]) => path.includes(`/everview_photos_webp/${subfolder}/`))
    .sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true }));

  return entries.map(([path, url]) => {
    const parts = path.split("/");
    const file = parts[parts.length - 1] || "";
    const slug = file.replace(/\.(webp|jpg|jpeg|png)$/i, "");
    const dims = DIMENSIONS[slug];
    return {
      slug,
      src: url,
      title: titleFromFilename(file),
      category: effectiveCategory,
      subfolder,
      folders: [subfolder],
      thumbSrc: resolveDerivative(path, THUMBS_BY_KEY),
      leadSrc: resolveDerivative(path, LEADS_BY_KEY),
      midSrc: resolveDerivative(path, MIDS_BY_KEY),
      width: dims?.width,
      height: dims?.height,
      // author: leave undefined here; preserve your upstream logic if you set it
    } as PhotoBase;
  });
}

/**
 * Automatically load ALL images from ANY depth under the root.
 * Useful for Gallery pages where you want everything without lists.
 */
export function loadAllBasesAuto(): PhotoBase[] {
  return Object.entries(ALL_IMAGES)
    .sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true }))
    .map(([path, url]) => {
      // path like: /src/assets/everview_photos_webp/bedrooms/master-suite/bed-1.webp
      const parts = path.split("/");
      const file = parts[parts.length - 1] || "";
      const slug = file.replace(/\.(webp|jpg|jpeg|png)$/i, "");

      // find folders after "everview_photos_webp"
      const rootIdx = parts.indexOf("everview_photos_webp");
      const folders = rootIdx >= 0 ? parts.slice(rootIdx + 1, parts.length - 1) : [];
      const primary = folders[0] || "gallery";
      const dims = DIMENSIONS[slug];

      return {
        slug,
        src: url,
        title: titleFromFilename(file),
        category: toTitleCase(primary),
        subfolder: primary,
        folders,
        thumbSrc: resolveDerivative(path, THUMBS_BY_KEY),
        leadSrc: resolveDerivative(path, LEADS_BY_KEY),
        midSrc: resolveDerivative(path, MIDS_BY_KEY),
        width: dims?.width,
        height: dims?.height,
        // author: leave undefined; your pipeline can still set it elsewhere
      } as PhotoBase;
    });
}

/**
 * Helper: load multiple known subfolders and flatten.
 */
export function loadAllBasesFrom(
  folders: string[],
  withCategory?: Record<string, string>
): PhotoBase[] {
  return folders.flatMap((f) => loadBasesFrom(f, withCategory?.[f]));
}


/* ------------------------------------------------------------------ *
 * Folder-addressed loading (MIS — the house, level by level)
 *
 * Photographs live under src/assets/everview_photos_webp in a folder tree
 * that mirrors the house:
 *
 *   bedroom-level/            <- photos loose here belong to the level
 *     master-suite/           <- and photos here belong to that space
 *     ocean-king/
 *     ...
 *   living-level/
 *   garden-level/
 *   exterior/
 *   views/
 *
 * Moving a file between folders is the whole editing interface: the section
 * a photograph appears in is decided by where it sits, never by matching
 * keywords against its filename. Re-run `node scripts/generate-thumbnails.mjs`
 * after moving anything.
 * ------------------------------------------------------------------ */

const ROOT_SEGMENT = "/everview_photos_webp/";

/** "…/everview_photos_webp/living-level/kitchen/kitchen-7.webp" -> "living-level/kitchen" */
function folderPathOf(path: string): string {
  const idx = path.indexOf(ROOT_SEGMENT);
  if (idx < 0) return "";
  const rel = path.slice(idx + ROOT_SEGMENT.length);
  const parts = rel.split("/");
  parts.pop();
  return parts.join("/");
}

function baseFromEntry(path: string, url: string): PhotoBase {
  const file = path.split("/").pop() || "";
  const slug = file.replace(/\.(webp|jpg|jpeg|png)$/i, "");
  const folderPath = folderPathOf(path);
  const folders = folderPath ? folderPath.split("/") : [];
  const dims = DIMENSIONS[slug];

  return {
    slug,
    src: url,
    title: titleFromFilename(file),
    category: toTitleCase(folders[folders.length - 1] || folders[0] || "gallery"),
    subfolder: folders[0] || "gallery",
    folders,
    folderPath,
    leafFolder: folders.length > 1 ? folders[folders.length - 1] : "",
    thumbSrc: resolveDerivative(path, THUMBS_BY_KEY),
    leadSrc: resolveDerivative(path, LEADS_BY_KEY),
    midSrc: resolveDerivative(path, MIDS_BY_KEY),
    width: dims?.width,
    height: dims?.height,
  };
}

const ALL_BASES: PhotoBase[] = Object.entries(ALL_IMAGES)
  .sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true }))
  .map(([path, url]) => baseFromEntry(path, url));

/**
 * Every photograph sitting directly in `folder` (no descendants).
 * `folder` is a path under the root, e.g. "living-level/kitchen" — or
 * "bedroom-level" for the photographs a level holds loose, not yet sorted
 * into one of its spaces.
 */
export function loadBasesInFolder(folder: string): PhotoBase[] {
  return ALL_BASES.filter((b) => b.folderPath === folder);
}

/** Every photograph in `folder` and everything beneath it. */
export function loadBasesUnderFolder(folder: string): PhotoBase[] {
  return ALL_BASES.filter(
    (b) => b.folderPath === folder || (b.folderPath ?? "").startsWith(`${folder}/`)
  );
}

/** The whole set, in folder/filename order. */
export function loadAllBases(): PhotoBase[] {
  return ALL_BASES;
}
